apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nuclio-playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nuclio-playground
    spec:
      containers:
      - name: nuclio-playground
        image: nuclio/playground:0.1.0-amd64
        ports:
        - containerPort: 8070
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - name: nuclio-docker-keys
          mountPath: "/etc/nuclio/playground/docker-keys"
          readOnly: true
        env:
        - name: NUCLIO_PLAYGROUND_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: "nuclio-registry"
              key: "registry_url"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: nuclio-docker-keys
        secret:
          secretName: nuclio-docker-keys
---
apiVersion: v1
kind: Service
metadata:
  name: nuclio-playground
spec:
  selector:
    app: nuclio-playground
  type: NodePort
  ports:
  - name: http
    port: 8070
    protocol: TCP
    nodePort: 32050
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nuclio-playground-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nuclio-playground
          servicePort: http
        path: /*
