apiVersion: v1
description: Serverless for Real-Time and Data-Driven Applications
name: nuclio
version: 0.4.3
appVersion: 1.1.5
icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
home: https://nuclio.io
sources:
  - https://github.com/nuclio/nuclio
maintainers:
  - name: bivas
    email: eliranb@iguazio.com
  - name: Eran Duchan
    email: erand@iguazio.com
  - name: Lev Radomislensky
    email: levr@iguazio.com
