apiVersion: v1
description: Serverless for Real-Time and Data-Driven Applications
name: nuclio
version: 0.10.1
appVersion: 1.7.1
icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
home: https://nuclio.io
sources:
  - https://github.com/nuclio/nuclio
maintainers:
  - name: Eran Duchan
    email: erand@iguazio.com
  - name: Oded Messer
    email: odedm@iguazio.com
  - name: Liran Ben Gida
    email: liranb@iguazio.com
  - name: Sahar Elhayani
    email: sahare@iguazio.com
