# Copyright 2017 The Nuclio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.autoscaler.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "nuclio.scalerName" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        nuclio.io/app: autoscaler
        nuclio.io/class: service
        nuclio.io/name: {{ template "nuclio.scalerName" . }}
      annotations:
        nuclio.io/version: {{ .Values.autoscaler.image.tag }}
    spec:
      serviceAccountName: {{ template "nuclio.serviceAccountName" . }}
      containers:
      - name: {{ template "nuclio.scalerName" . }}
        image: {{ .Values.autoscaler.image.repository }}:{{ .Values.autoscaler.image.tag }}
        imagePullPolicy: {{ .Values.autoscaler.image.pullPolicy }}
        env:
        {{- if .Values.autoscaler.namespace }}
        - name: NUCLIO_SCALER_NAMESPACE
          value: {{ .Values.autoscaler.namespace | quote }}
        {{- end }}
        {{- if .Values.platform }}
        volumeMounts:
        - name: platform-config
          mountPath: /etc/nuclio/config/platform
        {{- end }}
      {{- if .Values.platform }}
      volumes:
      - name: platform-config
        configMap:
          name: {{ template "nuclio.platformName" . }}
      {{- end }}
{{- end }}
